language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script: ./travis.sh
env:
  - TESTS=ci

  - TESTS=ruling
    SQ_VERSION=LTS

  - TESTS=ruling
    SQ_VERSION=LATEST_RELEASE

  - TESTS=ruling
    SQ_VERSION=DEV

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
